print('Fill in the blanks.')
print('Silly Word')
silly1=input()
print('Last Name')
name= input()
print('Illness')
illness=input()
print('Plural Noun')
noun=input()
print('Adjective')
adj1=input()
print('Adjective')
adj2=input()
print('Silly Word')
silly2=input()
print('Place')
place=input()
print('Number')
num=input()
print('Adjective')
adj3=input()
phrase = silly1,name,'will not be attending school today.He/she has come down with a case of',illness,'and has horrible',noun,'and a/an',adj1,
    'fever. We have made an appointment with the',adj2,'Dr.',silly2,', who studied for many years in',place,'and has',num,
    'degrees in pediatrics. He will send you all the information you need. Thank you!')
print('Dear School Nurse:'
print(phrase)
print('Sincerely')
print('Mrs. Wholesale.')
